name: md
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - ambertools=23.6=cuda_None_nompi_py310ha112c55_105
  - arpack=3.9.1=nompi_h77f6705_101
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - biopython=1.84=py310hc51659f_0
  - blas=1.0=openblas
  - blosc=1.21.6=hef167b5_0
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.3=h4bc722e_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cached-property=1.5.2=py_0
  - cairo=1.18.2=h5e7d6dc_0
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cftime=1.6.2=py310ha9d4c09_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.3=py310hea249c9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - fasteners=0.16.3=pyhd3eb1b0_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=hd4cb3f1_4
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.82.2=h44428e9_0
  - glib-tools=2.82.2=h4833e2c_0
  - glm=0.9.9.8=h00ab1b0_0
  - graphite2=1.3.13=h59595ed_1003
  - griddataformats=1.0.2=pyhd8ed1ab_0
  - gsd=3.3.0=py310h261611a_0
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - h5py=3.11.0=nompi_py310hf054cd7_102
  - harfbuzz=9.0.0=hda332d3_1
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=py310h06a4308_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=23_linux64_openblas
  - libboost=1.84.0=h0ccab89_4
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcap=2.71=h39aace5_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.9.0=hdb1bdb2_0
  - libdeflate=1.20=hd590300_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.82.2=h2ff4ddf_0
  - libglu=9.0.0=ha6d2627_1004
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.2.0=h77fa898_1
  - libgpg-error=1.51=hbd13f7d_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=23_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm19=19.1.2=ha7bfdaf_0
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.6=h035377e_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.9=h2774228_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=h4ab18f5_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.8.4=py310h1128e8f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_0
  - mdahole2-base=0.5.0=pyhd8ed1ab_1
  - mdanalysis=2.8.0=py310h5eaa309_0
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - mrcfile=1.5.2=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py310hd09550d_0
  - mysql-common=9.0.1=h266115a_3
  - mysql-libs=9.0.1=he0572af_3
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf-fortran=4.6.1=nompi_h228c76a_104
  - netcdf4=1.7.1=nompi_py310hf3005e6_101
  - networkx=3.3=py310h06a4308_0
  - nspr=4.36=h5888daf_0
  - nss=3.107=hdf54f9c_0
  - numexpr=2.8.7=py310h286c3b5_0
  - numpy=1.26.4=py310heeff2f4_0
  - numpy-base=1.26.4=py310h8a23956_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.1=py310h06a4308_0
  - pandas=2.2.2=py310h6a678d5_0
  - parmed=4.2.2=py310hc6cd4ac_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pathsimanalysis=1.2.0=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - perl=5.34.0=h5eee18b_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py310hebfe307_0
  - pip=24.0=py310h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.0.1=py310hff52083_1008
  - prompt-toolkit=3.0.47=pyha770c72_0
  - propka=3.5.1=pyhecae5ae_2
  - psutil=6.0.0=py310hc51659f_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pyedr=0.8.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pymol-open-source=3.0.0=py310h200f838_8
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=4_cp310
  - pytng=0.3.3=py310h6ea5394_0
  - pytz=2024.1=py310h06a4308_0
  - pyzmq=26.0.3=py310h6883aea_0
  - qt-main=5.15.8=h3155989_26
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.4.2=py310h1128e8f_1
  - scipy=1.13.1=py310heeff2f4_0
  - seaborn=0.13.2=py310h06a4308_0
  - setuptools=69.5.1=py310h06a4308_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=ha2e4443_0
  - sqlite=3.31.1=h7b6447c_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tornado=6.4.1=py310hc51659f_0
  - tqdm=4.66.4=py310h2f386ee_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - waterdynamics=1.2.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py310h06a4308_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - amberutils==21.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - defusedxml==0.7.1
      - dynetan==2.2.0
      - edgembar==0.2
      - einops==0.8.0
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - h11==0.14.0
      - html2text==2024.2.26
      - httpcore==1.0.5
      - httpx==0.27.2
      - idna==3.8
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - mistune==3.0.2
      - mmpbsa-py==16.0
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nglview==3.1.2
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - overrides==7.7.0
      - packmol-memgen==2024.2.9
      - pandocfilters==1.5.1
      - pdb4amber==22.0
      - prometheus-client==0.20.0
      - pycparser==2.22
      - pydssp==0.9.0
      - pymsmt==22.0
      - python-json-logger==2.0.7
      - python-louvain==0.16
      - pytraj==2.0.6
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - sander==22.0
      - send2trash==1.8.3
      - snapgene-reader==0.1.21
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.4.0
      - triton==3.0.0
      - types-python-dateutil==2.9.0.20240821
      - uri-template==1.3.0
      - urllib3==2.2.2
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - xmltodict==0.14.2
prefix: /gene/home/cjn/miniconda3/envs/md
